/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bbc8d0",
        "primary-container": "#1a2429",
        "tertiary-container": "#3b2e1f",
        "on-secondary-container": "#afcbd8",
        "on-tertiary-fixed-variant": "#534434",
        "tertiary-fixed-dim": "#d8c3ae",
        "on-tertiary-fixed": "#25190c",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#191c1d",
        "inverse-on-surface": "#191c1d",
        "primary-fixed": "#d7e4ec",
        "surface-container": "#212425",
        "surface": "#111415",
        "on-primary-fixed-variant": "#3c494f",
        "secondary-container": "#304a55",
        "on-tertiary-container": "#a89581",
        "on-primary": "#111d23",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-dim": "#111415",
        "primary": "#d7e4ec",
        "secondary": "#afcbd8",
        "on-secondary-fixed": "#021f29",
        "on-secondary-fixed-variant": "#304a55",
        "on-surface": "#e1e3e4",
        "secondary-fixed": "#cbe7f5",
        "tertiary-fixed": "#f5dfc8",
        "surface-container-lowest": "#0c0f10",
        "background": "#111415",
        "outline": "#8d9294",
        "tertiary": "#f5dfc8",
        "on-primary-fixed": "#111d23",
        "on-surface-variant": "#c3c7ca",
        "inverse-surface": "#e1e3e4",
        "surface-container-highest": "#323537",
        "surface-container-high": "#272a2b",
        "error": "#ffb4ab",
        "on-secondary": "#1a333e",
        "on-error": "#690005",
        "outline-variant": "#43474a",
        "on-primary-container": "#bbc8d0",
        "surface-bright": "#373a3b",
        "inverse-primary": "#546067",
        "surface-tint": "#bbc8d0",
        "on-background": "#e1e3e4",
        "secondary-fixed-dim": "#afcbd8",
        "surface-variant": "#43474a"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "1rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
